services:
  # postgres:
  #   image: postgres:17-alpine
  #   restart: always
  #   container_name: howl-postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
    # networks:
    #   - howl-network
#   server:
#     container_name: howl-server
#     build:
#       context: .
#       dockerfile: ./apps/server/Dockerfile
#     ports:
#       - "3001:3001"
#     depends_on:
#       - postgres
#     env_file:
#       - ./apps/server/.env
#     volumes:
#       - ./apps/server/.env:/app/.env
#     networks:
#       - howl-network
  frontend:
    container_name: howl-frontend
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
      args:
        VITE_API_BASE: http://localhost:3001
    ports:
      - "3000:3000"
    # depends_on:
    #   - server
    environment:
      - NODE_ENV=production
      - VITE_API_BASE=http://localhost:3001
    # networks:
    #   - howl-network
# volumes:
#   pgdata:
# networks:
#   howl-network:
#     driver: bridge