services:
  postgres:
    image: postgres:17-alpine
    restart: always
    container_name: howl-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - howl-network
  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./packages/server/.env:/app/.env
    networks:
      - howl-network

networks:
  howl-network:
    driver: bridge